version: "3.9"
services:
  feynman-technique-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feynman-technique-scraper
    restart: always
    ports:
      - '6200:6200'
    networks:
      - ft-network
    volumes:
      - feynman-technique-scraper-data:/data
volumes:
  feynman-technique-scraper-data:
networks:
    ft-network:
        external: true